<?php
/**
 * @file
 * Contains Group's implementation of the Node module hooks and forms.
 *
 * Please note that this is an additional layer on top of the Entity
 * implementation. For instance: we do not need hook_node_delete() because
 * our implementation of hook_entity_delete() covers everything.
 */

/**
 * In safe mode we prevent other modules overriding group permission control.
 */
define('GROUP_NODE_SAFE_MODE', 'GROUP_NODE_SAFE_MODE');

/**
 * In compliance mode we allow other modules to provide node access records
 * which might conflict with Group Node's access records. This is better Drupal
 * behaviour but might confuse some users.
 */
define('GROUP_NODE_COMPLIANCE_MODE', 'GROUP_NODE_COMPLIANCE_MODE');

/**
 * Mode which only allows a node to be in one group.
 */
define('GROUP_NODE_SINGLE_GROUPS_MODE', 'GROUP_NODE_SINGLE_GROUPS_MODE');

/**
 * Mode which allows a node to be in multiple group.
 */
define('GROUP_NODE_MULTIPLE_GROUPS_MODE', 'GROUP_NODE_MULTIPLE_GROUPS_MODE');

/**
 * Load our router functions without polluting the .module file.
 */
require_once 'gnode.router.inc';

/**
 * Load our mode functions without polluting the .module file.
 */
require_once 'modes/gnode.safe.inc';
require_once 'modes/gnode.compliance.inc';

/**
 * Get the currently set mode of the gnode module.
 *
 * @return
 *   Either GROUP_NODE_SAFE_MODE or GROUP_NODE_COMPLIANCE_MODE
 */
function _gnode_get_mode() {
  return variable_get('group_node_mode', GROUP_NODE_SAFE_MODE);
}

/**
 * Determine if gnode is in multiple mode.
 *
 * @return bool
 *   TRUE if a node can be placed within multiple groups.
 *   FALSE if a node can only be placed in a single group.
 */
function _gnode_is_multiple() {
  $multiple_mode = variable_get('group_node_multiple_groups', GROUP_NODE_SINGLE_GROUPS_MODE);
  return $multiple_mode === GROUP_NODE_MULTIPLE_GROUPS_MODE;
}

/**
 * Implements hook_entity_info_alter().
 */
function gnode_entity_info_alter(&$entity_info) {
  $entity_info['node']['group entity'] = _gnode_is_multiple() ? 'multiple' : 'single';
}

/**
 * Implements hook_group_permission().
 *
 * Polyfills permissions for the Node module and can therefore not reside
 * inside the gnode.group.inc file.
 */
function node_group_permission() {
  $permissions = array();

  foreach (node_type_get_types() as $node_type) {
    $replace = array('%node_type' => $node_type->name);

    $permissions["view $node_type->type node"] = array(
      'title' => t('%node_type: View content', $replace),
    );
    $permissions["create $node_type->type node"] = array(
      'title' => t('%node_type: Create new content', $replace),
    );
    $permissions["update own $node_type->type node"] = array(
      'title' => t('%node_type: Edit own content', $replace),
    );
    $permissions["update any $node_type->type node"] = array(
      'title' => t('%node_type: Edit any content', $replace),
    );
    $permissions["delete own $node_type->type node"] = array(
      'title' => t('%node_type: Delete own content', $replace),
    );
    $permissions["delete any $node_type->type node"] = array(
      'title' => t('%node_type: Delete any content', $replace),
    );
  }

  return $permissions;
}

/**
 * Implements hook_admin_paths().
 */
function gnode_admin_paths() {
  if (variable_get('node_admin_theme')) {
    return array('group/*/node/add/*' => TRUE);
  }
}

/**
 * Retrieve all group ids a user can create a node of a given type in.
 *
 * @param string $type
 *   The node type the user is attempting to create.
 * @param object $account
 *   (optional) The account of the user.
 *
 * @return array
 *   An array of group ids (gids).
 */
function gnode_group_node_create_gids($type, $account = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }

  // Determine whether the account could be 'anonymous' or 'outsider'.
  $account_exists = (bool) $account->uid;

  // If the user can bypass group access, return all group ids.
  if (user_access('bypass group access', $account)) {
    return db_select('groups', 'g')->fields('g')->execute()->fetchCol();
  }

  // Otherwise, start gathering group ids.
  $gids = array();

  // Check for all group types if a non-member can create nodes of the given
  // node type in them.
  foreach (group_types() as $group_type) {
    // Retrieve the permissions to check for creation rights.
    $check_permissions = $account_exists ? $group_type->outsider_permissions : $group_type->anonymous_permissions;

    $has_access = in_array('administer group', $check_permissions);
    $has_access = $has_access || in_array("create $type", $check_permissions);

    // If the group type allows access to non-members, we add all of the groups
    // the user is not a member of. This would be all groups in case we are
    // checking for an anonymous user.
    if ($has_access) {
      $gids = array_merge($gids, group_non_member_gids($account->uid, $group_type->name));
    }
  }

  // Add all of the user's groups in which he has creation rights.
  foreach (group_load_by_member($account->uid) as $group) {
    $has_access = group_access('administer group', $group, $account);
    $has_access = $has_access || group_access("create $type node", $group, $account);

    if ($has_access) {
      $gids[] = $group->gid;
    }
  }

  $gids = array_unique($gids);
  sort($gids);

  return $gids;
}

/**
 * Determines whether a user could create a node in a Group context.
 *
 * @param string $type
 *   The node type the user is attempting to create.
 * @param object $account
 *   (optional) The account of the user.
 *
 * @return bool
 *   Whether the user has creation rights.
 */
function gnode_group_node_create_access($type, $account = NULL) {
  // This flag can be manipulated to not have Group Node interfere with the
  // results of hook_node_access(). This can be useful if you need to figure
  // out whether a user had node creation rights before Group Node decided
  // to allow such action.
  $skip = &drupal_static(__FUNCTION__, FALSE);

  if ($skip) {
    return FALSE;
  }

  global $user;
  if (!isset($account)) {
    $account = $user;
  }

  // If the user can bypass group access, he is allowed access.
  if (user_access('bypass group access', $account)) {
    return TRUE;
  }

  // Determine whether the account could be 'anonymous' or 'outsider'.
  $account_exists = (bool) $account->uid;

  // Check for all group types if a non-member can create nodes of the given
  // node type in them.
  foreach (group_types() as $group_type) {
    // Retrieve the permissions to check for creation rights.
    $check_permissions = $account_exists ? $group_type->outsider_permissions : $group_type->anonymous_permissions;

    $has_access = in_array('administer group', $check_permissions);
    $has_access = $has_access || in_array("create $type node", $check_permissions);

    // If the group type allows access to non-members and the provided user
    // has as at least one group of this type he is not a member of, we allow
    // access.
    if ($has_access && group_non_member_gids($account->uid, $group_type->name)) {
      return TRUE;
    }
  }

  // Check the user's groups for creation rights.
  foreach (group_load_by_member($account->uid) as $group) {
    $has_access = group_access('administer group', $group, $account);
    $has_access = $has_access || group_access("create $type node", $group, $account);

    if ($has_access) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Determines whether a user could create a node in a site-wide context.
 *
 * This function does not take Group Node's hook_node_access() implementation
 * into account. It just figures out if a user can create a node outside of any
 * Group entity.
 *
 * This is mostly useful because in order to have Node behave properly, we need
 * to implement hook_node_access() just a little too permissive, making it hard
 * to find out what rights the user had before we started interfering.
 *
 * @param string $type
 *   The node type the user is attempting to create.
 * @param object $account
 *   (optional) The account of the user.
 *
 * @return bool
 *   Whether the user has creation rights.
 */
function gnode_global_node_create_access($type, $account = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }

  // In order to figure out whether the user can create nodes outside of a
  // group, we first have to delete the cached node_access entry for this node
  // type.
  $rights = &drupal_static('node_access', array());
  unset($rights[$account->uid][$type]['create']);

  // Then we flag gnode_group_node_create_access() to not interfere with the
  // results of node_access() and run the latter to get the result we want.
  $skip = &drupal_static('gnode_group_node_create_access');
  $skip = TRUE;
  $return = node_access('create', $type);

  // After we have established whether the user has global node creation
  // rights, we need to once again unflag gnode_group_node_create_access() and
  // remove the node type's (skewed) entry from the node_access() cache.
  $skip = FALSE;
  unset($rights[$account->uid][$type]['create']);

  // After all this, it is safe to return the retrieved result.
  return $return;
}

/**
 * Get a list of all the group ids a node is within.
 *
 * This normalises the group parameter on a node as this can be either a single
 * value if gnode module is configured so that nodes can have only one parent or
 * an array of values if a node can have multiple parents.
 *
 * @param $node
 *
 * @return int[]
 */
function gnode_node_group_ids($node) {
  if (empty($node->group)) {
    return array();
  }

  return is_array($node->group) ? $node->group : array($node->group);
}

/**
 * Get a list of all group entities a node is within.
 *
 * @param $node
 *
 * @return Group[]
 */
function gnode_node_groups($node) {
  return group_load_multiple(gnode_node_group_ids($node));
}

/**
 * Implements hook_node_access().
 *
 * Because the grant system for node access can quickly become very taxing on
 * the site's performance, we chose to implement hook_node_access() instead.
 *
 * All list query related alterations that would otherwise be taken care of by
 * the grant system still take place, albeit in Group Node's implementation of
 * hook_query_TAG_alter() for 'node_access'.
 *
 * @see gnode_query_node_access_alter()
 */
function gnode_node_access($node, $op, $account) {
  if (_gnode_get_mode() === GROUP_NODE_COMPLIANCE_MODE && $op !== 'create') {
    return NODE_ACCESS_IGNORE;
  }

  if (is_string($node)) {
    if ($op == 'create') {
      if (gnode_group_node_create_access($node, $account)) {
        return NODE_ACCESS_ALLOW;
      }
    }
  }

  // Make sure we are dealing with a group node.
  if (empty($node->group)) {
    return NODE_ACCESS_IGNORE;
  }

  // If the user can bypass group access, he is allowed access.
  if (user_access('bypass group access', $account)) {
    return NODE_ACCESS_ALLOW;
  }

  foreach (gnode_node_groups($node) as $group) {

    if (group_access('administer group', $group, $account)) {
      return NODE_ACCESS_ALLOW;
    }

    switch ($op) {
      case "view":
        if (group_access("view $node->type node", $group, $account)) {
          return NODE_ACCESS_ALLOW;
        }
        break;

      case "update":
      case "delete":
        if (group_access("$op any $node->type node", $group, $account)) {
          return NODE_ACCESS_ALLOW;
        }

        if ($account->uid == $node->uid && group_access("$op own $node->type node", $group, $account)) {
          return NODE_ACCESS_ALLOW;
        }

        break;
    }
  }

  return NODE_ACCESS_DENY;
}

/**
 * Adds group data to the node add form.
 *
 * @param Group $group
 *   The group to create the node for.
 * @param string $node_type
 *   The type of node to create for the group.
 *
 * @return array
 *   Returns the node editing form.
 *
 * @see node_add()
 */
function gnode_node_add(Group $group, $node_type) {
  global $user;

  // Create an empty node to pass on to the node form.
  $types = node_type_get_types();
  $node = (object) array(
    'uid' => $user->uid,
    'name' => (isset($user->name) ? $user->name : ''),
    'type' => $node_type,
    'language' => LANGUAGE_NONE,
    'group' => $group->gid,
  );

  // Set the page title to something different than the local action title.
  $message = 'Create @name in @group';
  $replace = array('@name' => $types[$node_type]->name, '@group' => $group->label());
  drupal_set_title(t($message, $replace), PASS_THROUGH);

  // Build the arguments to set in the form state. We ensure any extra URL
  // parameters will be passed on to the form builder as well. For instance:
  // group/1/node/add/page/specialvar will pass on the empty 'page' node as well
  // as the string "specialvar".
  $setup = array($node);
  $extra = array_slice(func_get_args(), 2);
  $args = array_merge($setup, $extra);

  // Build the form state, paying extra attention to two things: setting the
  // arguments as explained above and making sure the form will know to load
  // node.pages.inc whenever it's rebuilt.
  $form_state['build_info']['args'] = array_values($args);
  form_load_include($form_state, 'inc', 'node', 'node.pages');

  // Finally we build the form with our customized form state.
  return drupal_build_form($node_type . '_node_form', $form_state);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Adds a Group vertical tab to the node form.
 *
 * You can only select those groups that you can create nodes of this type in.
 * It would not make sense if someone could move nodes to a group where he does
 * not have creation rights.
 *
 * @see gnode_node_validate()
 * @see gnode_node_submit()
 */
function gnode_form_node_form_alter(&$form, $form_state) {
  global $user;

  $node = $form_state['node'];

  $groups = gnode_node_groups($node);
  $gids = array_keys($groups);

  $can_bypass_access = user_access('bypass group access');

  // If the user can't bypass group access, have a nid, and no gids, we
  // are on either on an ungrouped node edit form. In such a case we do not show
  // anything.
  if (!$can_bypass_access && empty($node->group) && !empty($node->nid)) {
    return;
  }

  // Otherwise add a vertical tab for group selection.
  $form['group_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Group settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#group' => 'additional_settings',
    '#attributes' => array(
      'class' => array('node-form-group-information'),
    ),
    '#attached' => array(
      'js' => array(drupal_get_path('module', 'gnode') . '/misc/gnode.js'),
    ),
    '#tree' => TRUE,
    '#weight' => -50,
  );

  $form['group_settings']['existing_gids'] = array(
    '#type' => 'value',
    '#value' => $gids,
    '#parent' => array('group_settings'),
  );

  // Find out which form API element we should be using.
  $element_type = $can_bypass_access
    ? variable_get('gnode_group_choice_admin_element', 'auto_complete')
    : variable_get('gnode_group_choice_standard_element', 'select');

  // Use a helper function to generate the form element.
  $element_function = "_gnode_generate_node_form_group_{$element_type}_element";
  $element = function_exists($element_function) ? $element_function($node) : array();

  if (empty($element) || !is_array($element)) {
    // The user is not able to change the group for this node so don't show
    // the form controls.
    $form['group_settings']['#access'] = FALSE;
    return;
  }

  // Add the group select form element to the form.
  $form['group_settings'] += $element;
}

/**
 * Helper function to generate a form node element for selecting the group.
 *
 * @param $node
 *   The node whose edit form is being generated
 *
 * @return array
 *   Form API select element.
 */
function _gnode_generate_node_form_group_select_element($node) {
  $options = array();

  foreach (group_load_multiple(gnode_group_node_create_gids($node->type)) as $group) {
    if (empty($node->nid) || group_access('administer group', $group)) {
      // We only give the user the option to add or remove a node from a
      // group if they are a group administrator unless its a new node.
      $options[$group->gid] = $group->label();
    }
  }

  if (empty($options)) {
    return array();
  }

  $global_node_create_access = gnode_global_node_create_access($node->type);

  // If there is only one option and the user cannot create content outside the
  // group then the group control should be selected and disabled.
  $disabled = (count($options) === 1 && !$global_node_create_access);

  $default_gids = gnode_node_group_ids($node);

  if (!$global_node_create_access && empty($default_gids) && count($options) === 1) {
    $gids = array_keys($options);
    $default_gids = array(reset($gids));
  }

  $description = $global_node_create_access
    ? t('Optionally select the group to attach this node to.')
    : t('Because you are not allowed to create this content outside of a group, you are required to select one here.');

  return array(
    'gid' => array(
      '#type' => 'select',
      '#title' => t('Parent group'),
      '#description' => $description . '<br />' . _gnode_get_group_access_warning(),
      '#options' => $options,
      '#required' => !$global_node_create_access,
      '#multiple' => _gnode_is_multiple(),
      '#default_value' => $default_gids,
      '#empty_value' => '',
      '#disabled' => $disabled,
    ),
  );
}

/**
 * Function to generate a form node element for checkbox selection of the group.
 *
 * @param $node
 *   The node whose edit form is being generated
 *
 * @return array
 *   Form API select element.
 */
function _gnode_generate_node_form_group_checkbox_element($node) {
  $element = _gnode_generate_node_form_group_select_element($node);

  if (empty($element)) {
    return $element;
  }

  if (_gnode_is_multiple()) {
    // If nodes can be in many groups then use checkboxes.
    $element['gid']['#type'] = 'checkboxes';
  }
  else {
    // If nodes can be in only one group then use radio buttons.
    $element['gid']['#type'] = 'radios';

    if (empty($element['gid']['#required'])) {
      // If not required add a none option.
      $element['gid']['#options'] = array(0 => t('None')) + $element['gid']['#options'];
      if (empty($element['gid']['#default_value'])) {
        $element['gid']['#default_value'] = array('0');
      }
    }

    // Set the default value to be a single value.
    $element['gid']['#default_value'] = reset($element['gid']['#default_value']);
  }

  return $element;
}

/**
 * Helper function to generate a form node auto complete element.
 *
 * @param $node
 *   The node whose edit form is being generated
 *
 * @return array
 *   Form API select element.
 */
function _gnode_generate_node_form_group_auto_complete_element($node) {
  $global_node_create_access = gnode_global_node_create_access($node->type);
  $groups = gnode_node_groups($node);

  $group_names = array();

  foreach ($groups as $gid => $group) {
    // Retrieve the default value for the auto complete field.
    $title = $group->label();
    $group_names[] = "$title (GID: $gid)";
  }

  $group_name = implode(', ', $group_names);

  $description = $global_node_create_access
    ? t('Enter the name of the group to attach this node to. Leave blank for no group.')
    : t('Because you are not allowed to create this content outside of a group, you are required to enter the name of one here.');

  // There is a special use case where a user may edit global nodes, but
  // not create them and also may bypass group access. In such a case, he
  // could move an ungrouped node to a group, or leave it ungrouped.
  if (!empty($node->nid) && empty($gids) && !$global_node_create_access) {
    $description = t('This node is not attached to a group. In order to keep it that way, leave this field blank. Alternatively, you may enter the name of the group to attach this node to.');
    $description .= '<br /><strong>' . t('Warning') .  '</strong>: ' . t('Because you are not allowed to create this content outside of a group, you will not be able to move it back to the site wide scope.');
    $global_node_create_access = TRUE;
  }

  return array(
    'group_auto_complete' => array(
      '#type' => 'textfield',
      '#title' => t('Parent group'),
      '#autocomplete_path' => 'group/autocomplete',
      '#default_value' => $group_name,
      '#description' => $description . '<br />' . _gnode_get_group_access_warning(),
      '#required' => !$global_node_create_access,
      '#multiple' => _gnode_is_multiple(),
    ),
  );
}

/**
 * Retrieve the warning about node inheriting access control of the group.
 */
function _gnode_get_group_access_warning() {
  return '<strong>' . t("By selecting a group, the node will inherit the group's access control.") . '</strong>';
}

/**
 * Implements hook_node_validate().
 *
 * Validates and processes the 'parent group' field.
 *
 * @see gnode_form_node_form_alter()
 */
function gnode_node_validate($node, $form, &$form_state) {
  // If the user was presented with an autocomplete, we need to map the selected
  // group name to a group id in the form state so the submit handler can rely
  // on it being set.
  if (!empty($form_state['values']['group_settings']['group'])) {

    if (!empty($values['group_auto_complete'])) {
      // Retrieve the group id from the name suffix.
      if ($specified_gids = group_autocomplete_result_gid($form_state['values']['group_settings']['group_auto_complete'])) {
        $form_state['values']['group_settings']['gid'] = $specified_gids;
      }
      // Throw an error if the gid could not be retrieved.
      else {
        form_set_error('group_settings][group_auto_complete', t('Group name not found'));
      }
    }
  }
}

/**
 * Implements hook_node_submit().
 *
 * 1. Bypass group access users can set any groups for this node.
 * 2. If it is a new node, the user can add the node to any group they have
 *    create access to.
 * 3. If it is an existing node, the user can change the groups a node is in
 *    only for groups they are an administrator of.
 * 4. If the user cannot globally create nodes of this type then they must
 *    select at least one node.
 *
 * @see gnode_form_node_form_alter()
 */
function gnode_node_submit($node, $form, &$form_state) {
  if (!empty($form_state['values']['group_settings'])) {
    $has_bypass = user_access('bypass group access');
    $specified_gids = empty($form_state['values']['group_settings']['gid']) ? array() : $form_state['values']['group_settings']['gid'];

    $specified_gids = is_array($specified_gids) ? $specified_gids : array($specified_gids);
    $specified_gids = array_filter($specified_gids, '_gnode_specified_groups_result_clean');

    if (!$has_bypass && !empty($node->nid)) {
      // If the user is missing has_bypass then they cannot change the group
      // is in for groups they are not the administrator of.
      // The previous groups for this node are stored on the form.
      $existing_gids = $form_state['values']['group_settings']['existing_gids'];

      foreach ($existing_gids as $existing_gid) {
        if (!isset($specified_gids[$existing_gid])) {
          // This node is in a group the user is not an administrator of.
          $specified_gids[] = $existing_gid;
        }
      }
    }

    $node->group = _gnode_is_multiple() ? $specified_gids : reset($specified_gids);
  }
  elseif (isset($node->group)) {
    unset($node->group);
  }
}

/**
 * Array filter for results of the node form submission.
 *
 * We only want real group ids in the result.
 *
 * @see gnode_node_submit().
 */
function _gnode_specified_groups_result_clean($value) {
  return !empty($value) && is_numeric($value);
}
