<?php

/**
 * @file
 * Customizations for presenting a responsive Marketo form.
 */

include_once 'fnet_marketo_form.features.inc';

/**
 * Implements hook_preprocess_page().
 */
function fnet_marketo_form_preprocess_page(&$variables) {
  if (isset($variables['node']) && ($variables['node']->type == 'fnet_marketo_form')) {
    // TODO: Deprecated. Remove when be.mobilized is turned off.
    // Setting cookie to stop be.mobilized from serving marketo form pages.
    setcookie('fullweb', 1, 0, '/');

    $variables['title'] = html_entity_decode($variables['node']->title);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function fnet_marketo_form_preprocess_node(&$variables) {
  if (isset($variables['node']) && ($variables['node']->type == 'fnet_marketo_form')) {
    fnet_marketo_form_template_variables($variables);
    if (isset($variables['node']->field_fnet_mkto_adtracker[LANGUAGE_NONE][0]['value'])) {
      $variables['title_suffix'] = $variables['node']->field_fnet_mkto_adtracker[LANGUAGE_NONE][0]['value'];
    }
    // Add js for prefill forms.
    drupal_add_js(drupal_get_path('module', 'fnet_marketo_form') . '/js/teknkl-simpledto-1.0.2.js');
    drupal_add_js('//app-sjo.marketo.com/js/forms2/js/forms2.min.js', 'external');
  }
}

/**
 * Implements hook_page_build().
 */
function fnet_marketo_form_page_build(&$page) {
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nodeId = arg(1);
    $nodetype = isset($page['content']['system_main']['nodes'][$nodeId]['field_removenav']['#object']->type) ? $page['content']['system_main']['nodes'][$nodeId]['field_removenav']['#object']->type : '';

    if (isset($nodeId) && $nodetype == 'fnet_marketo_form') {
      $tracking_code = isset($page['content']['system_main']['nodes'][$nodeId]['#node']->field_fnet_mkto_adtracker[LANGUAGE_NONE][0]['value']) ? trim($page['content']['system_main']['nodes'][$nodeId]['#node']->field_fnet_mkto_adtracker[LANGUAGE_NONE][0]['value']) : '';

      if ($tracking_code) {
        $page['page_bottom']['fnet_marketo_form'] = array('#markup' => $tracking_code);
      }
    }
  }
}

/**
 * Assign variables for rendering marketo form template.
 */
function fnet_marketo_form_template_variables(&$variables) {
  global $language;
  $currlang = $language->language;
  $node = $variables['node'];

  if ($node->field_fnet_mkto_export_ctrl[$currlang][0]['value'] == "1") {
    if (function_exists('findit_get_client_ip')) {
      $ip_address = findit_get_client_ip();
      $ip_embargoed = findit_embargoed_ip_address($ip_address);
    }
    else {
      $ip_embargoed = FALSE;
    }
  }
  else {
    $ip_embargoed = FALSE;
  }

  // Boolean indicating if use if from embargoed country.
  $variables['ip_embargoed'] = $ip_embargoed;
  // The Marketo form number.
  if (isset($node->field_fnet_mkto_form_number[$currlang][0]['value'])) {
    $variables['form_number'] = $node->field_fnet_mkto_form_number[$currlang][0]['value'];
  }
  else {
    $variables['form_number'] = $node->field_fnet_mkto_form_number['en'][0]['value'];
  }
  // The url to redirect to after the Marketo form is submitted.
  if (isset($node->field_fnet_mkto_form_url[$currlang][0]['url'])) {
    $variables['follow_up_url'] = $node->field_fnet_mkto_form_url[$currlang][0]['url'];
  }
  else {
    $variables['follow_up_url'] = $node->field_fnet_mkto_form_url['en'][0]['url'];
  }
  // The Marketo instance key.
  $variables['marketo_key'] = variable_get('marketo_api_munchkin_key', '709-HGB-925');

  // The Marketo Prefill Unifying Domains and their Marketo counterparts.
  $environments = array(
    'live' => "//info.flukenetworks.com/Form-Prefill-Guided-Landing-Page.html",
    'test' => "//info-test.flukenetworks7tst.danahertm.com/Test_embedded-form-LP.html",
    'dev-' => "//info-test.flukenetworks7dev.danahertm.com/Test_embedded-form-LP.html",
    'local' => "//info-test.flukenetworks7dev.danahertm.com/Test_embedded-form-LP.html",
  );

  // Get the current server protocol, subdomain, and domain.
  preg_match('/(https?\:\/\/)?(.+?\.)([^\/]*)/', $GLOBALS['base_url'], $matches);
  $domain = $matches[3];
  // Match Pantheon environment to correct Marketo counterpart.
  if (strpos($domain, 'pantheon') !== FALSE) {
    $env = substr($matches[2], 0, 4);
  }
  // Match production environment to Marketo counterpart.
  elseif (strpos($domain, 'flukenetworks') !== FALSE) {
    $env = 'live';
  }
  // Any other domains are considered local test environments.
  else {
    $env = 'local';
  }

  // Assign domain to a template variable.
  $variables['domain'] = $domain;

  // Change marketo instance template variable based on environment.
  $variables['marketo_lp'] = $environments[$env];
}
