<?php

/**
 * @file
 * Placeholder.
 */



function fnet_content_menu() {

    $items = array();

    $items['admin/fnet/content'] = array(
      'type' => MENU_NORMAL_ITEM,
      'title'   =>    t('FNET Content Types pages'),
      'access arguments' => array('administer site configuration'),
      'page callback' => '_fnet_content',
    );

    return $items;

}


function _fnet_content() {


  return '';

}

