<?php
// $Id: marketo_form.module 5830 2015-04-02 18:44:38Z jcaratoz $

include_once 'marketo_form.features.inc';

/**
 * Implements hook_menu().
 *
 * @return mixed
 */
function marketo_form_menu() {
  $items['admin/fnet/marketo_form'] = array(
    'title' => 'Marketo Form Footers',
    'description' => "Settings for marketo_form module.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('marketo_form_admin_form'),
    'access arguments' => array('administer marketo_form configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'marketo_form.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 *
 * @return array
 */
function marketo_form_permission() {
  return array(
    'administer marketo_form configuration' => array(
      'title' => t('administer marketo_form configuration'),
      'description' => t('administer marketo_form configuration'),
    ),
  );
}

/**
 * @return array
 */
function marketo_get_regions() {
  $regions = array(
    'en-us' => 'English/United States',
    'en-au' => 'English/Australia',
    'en-ca' => 'English/Canada',
    'en-eu' => 'English/Europe',
    'en-in' => 'English/India',
    'en-ln' => 'English/Latin America',
    'en-su' => 'English/Southeast Asia',
    'fr-eu' => 'French/Europe',
    'fr-ca' => 'French/Canada',
    'de-eu' => 'German/Europe',
    'es-eu' => 'Spanish/Europe',
    'es-ln' => 'Spanish/Latin America',
    'pt-eu' => 'Portuguese/Europe',
    'pt-br' => 'Portuguese/Brazil',
    'cn-zh' => 'Chinese/China',
    'jp-ja' => 'Japanese/Japan',
    'ko-kr' => 'Korean/Korea',
    'ru-ru' => 'Russian/Russia',
  );
  return $regions;
}

/**
 * Implements hook_preprocess_page().
 *
 * @param $variables
 */
function marketo_form_preprocess_page(&$variables) {
  if (isset($variables['node']) && ($variables['node']->type == 'marketo_form')) {
    // TODO: Deprecated. Remove when be.mobilized is turned off.
    //setting cookie to stop be.mobilized from serving marketo form pages
    setcookie('fullweb', 1, 0, '/');

    $variables['title'] = html_entity_decode($variables['node']->title);
    if (isset($variables['node']->field_banner_html[LANGUAGE_NONE][0]['value'])) {
      $variables['page']['highlighted'] = "<div style='margin-left:auto;margin-right:auto;width:1000px'>";
      $variables['page']['highlighted'] .= $variables['node']->field_banner_html[LANGUAGE_NONE][0]['value'];
      $variables['page']['highlighted'] .= "</div>";
    } else if (isset($variables['node']->field_image[LANGUAGE_NONE][0]['fid'])) {
      $file = file_load($variables['node']->field_image[LANGUAGE_NONE][0]['fid']);
      $uri = $file->uri;
      $url = file_create_url($uri);
      $variables['page']['highlighted'] = "<img src=\"".$url."\" alt=\"".$variables['node']->field_image[LANGUAGE_NONE][0]['alt']."\" title=\"".$variables['node']->field_image[LANGUAGE_NONE][0]['alt']."\" width=\"1000px\" border=\"0\" />";
    }

    /*
    if ($variables['node']->field_removenav[LANGUAGE_NONE][0]['value'] == "1") {
      $variables['page']['menu_bar'] = "";
      $variables['page']['footer'] = "";
    }
    */
  }
}

/**
 * Implements hook_preprocess_node().
 * @param $variables
 */
function marketo_form_preprocess_node(&$variables) {
  if (isset($variables['node']) && ($variables['node']->type == 'marketo_form')) {
    marketo_form_template_variables($variables);
    if (isset($variables['node']->field_tracking_code[LANGUAGE_NONE][0]['value'])) {
      $variables['title_suffix'] = $variables['node']->field_tracking_code[LANGUAGE_NONE][0]['value'];
    }
  }
}

function marketo_form_page_build(&$page) {
	if (arg(0) == 'node' && is_numeric(arg(1))) {
		$nodeId = arg(1);
		$nodetype = isset($page['content']['system_main']['nodes'][$nodeId]['field_removenav']['#object']->type)?$page['content']['system_main']['nodes'][$nodeId]['field_removenav']['#object']->type:'';
		if (isset($nodeId) && $nodetype=='marketo_form') {
			$tracking_code = isset($page['content']['system_main']['nodes'][$nodeId]['#node']->field_tracking_code['und'][0]['value'])?trim($page['content']['system_main']['nodes'][$nodeId]['#node']->field_mkt_form_adtracker['und'][0]['value']):'';
			if ($tracking_code) {
				$page['page_bottom']['marketo_form'] = array('#markup' => $tracking_code);
			}
		}
	}
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function marketo_form_get_form_html($iFrameUrl, $iFrameHeight) {
  if (empty($iFrameUrl)) {
    watchdog('marketo_form', "Empty iframe url", array(), WATCHDOG_WARNING);
    $html = '';
    return $html;
  }
  $ch = curl_init();
  $timeout = 10;
  $serverName = $_SERVER['HTTP_HOST'];
  $qStr = marketo_form_build_query_string();
  curl_setopt($ch, CURLOPT_URL, $iFrameUrl . $qStr);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);

  // This is how we preserve the form pre-fill and progressive profiling
  // features of Marketo:
  if (!empty($_COOKIE['_mkto_trk'])) {
    curl_setopt($ch, CURLOPT_COOKIE, '_mkto_trk=' . $_COOKIE['_mkto_trk']);
  }
  $html = curl_exec($ch);
  $result = curl_getinfo($ch);
  curl_close($ch);
  if (strpos($html, "404 Not Found")) {
    $html = '<p>Currently unavailable, please contact Fluke Networks Sales.</p>';
  }
  elseif ($result['http_code'] != 200) {
    watchdog('marketo_form', "Error fetching marketo form:\n %form \nReturn code: %code", array(
      '%form' => $iFrameUrl,
      '%code' => $result['http_code'],
    ), WATCHDOG_WARNING);
    $html = '<iframe id="myFrame" src="' . $iFrameUrl . $qStr . '" width="395" scrolling="no" marginwidth="0"';
    $html .= ' marginheight="0" frameborder="0" vspace="0" hspace="0" ';
    $html .= 'style="overflow:hidden; height:' . $iFrameHeight . '"></iframe>';
  }
  else {
    $myUrl = parse_url($iFrameUrl);
    $html = preg_replace('/(<!DOCTYPE html PUBLIC)(.*)(>)/', '', $html);
    $html = str_ireplace('<!DOCTYPE html>', '', $html); // Possible variation.
    $html = str_ireplace('<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">', '', $html);
    $html = str_ireplace('<html lang="en">', '', $html); // Possible variation.
    $html = str_ireplace('</html>', '', $html);
    $html = str_ireplace('<meta http-equiv="content-type" content="text/html; charset=UTF-8" />', '', $html);
    $html = str_ireplace('<head>', '', $html);
    $html = str_ireplace('</head>', '', $html);
//    $html = str_ireplace('<body id="bodyId" class="mktEditable">', '', $html);
//    $html = str_ireplace('<body id="bodyId" class="mktEditable" align="center" >', '', $html); // Possible variation.
    $html = preg_replace('/(<body)(.*)(>)/', '', $html);
    $html = str_ireplace('</body>', '', $html);
    $html = preg_replace('%src="//(.*)/%mU', 'src="http://\1/', $html);
    $html = str_ireplace('href="/', 'href="http://' . $myUrl["host"] . '/', $html);
    $html = str_ireplace('src="/', 'src="http://' . $myUrl["host"] . '/', $html);
    $html = preg_replace('/(name="_mkt_trk" value=")(id:[0-9A-Z]+\-[0-9A-Z]+\-[0-9A-Z]+)(")/', '${1}$3', $html);
    //$html = preg_replace('/([a-z\-]+)(\.marketo\.com)/', $myUrl["host"], $html);
    $html = preg_replace('/(<\!--Google -->)(.*)(urchinTracker)(.*)(-->)/s', '', $html);
//    $html = preg_replace('%<script type="text/javascript" src="http://info.flukenetworks.com/js/public/jquery-latest.min.js"></script>%im', '', $html);
    $html = preg_replace('%action="/%sim', 'action="http://info.flukenetworks.com/', $html);

    if (function_exists('findit_local_auth_cookie')) {
      $pattern = '%http://Support\.FlukeNetworks\.com/Find_It\.asp\?Src=FNet&Style=82&Document=(\d{0,9})%i';
      $replacement = 'http://' . $serverName . '/findit/' . '\1';
      $html = preg_replace($pattern, $replacement, $html);
      $serverName = strtr($serverName, array('.' => '\.'));
      $pattern = '%http://' . $serverName . '/findit/' . '([0-9]{0,9})%i';
      $matches = array();
      $found = preg_match($pattern, $html, $matches);
      if ($found) {
        $document_id = $matches[1];
        findit_local_auth_cookie($document_id);
      }
    }
  }
  return $html;
}

/**
 * @return string
 */
function marketo_form_build_query_string() {
  $query_string = "";
  $query_parameter = array();
  if (!empty($_SERVER['QUERY_STRING'])) {
    $pairs = explode("&", $_SERVER['QUERY_STRING']);
    foreach ($pairs as $pair) {
      list($variable, $value) = explode("=", $pair);
      if (in_array(strtolower($variable), array('document', 'ls', 'lsd', 'gclid', 'epi'))) {
        switch ($variable) {
          case 'document':
            if (!is_numeric($value)) {
              $value = '';
            }
            break;
          default:
            if ((strlen($value) > 256) || (stripos($value, '/proc') !== FALSE)) {
              $value = '';
            }
            break;
        }
        if (!empty($value)) {
          $query_string .= ((!empty($query_string)) ? '&' : '') . $variable . '=' . $value;
          $query_parameter[$variable] = $value;
        }
      }
    }
  }
  if ((isset($_COOKIE['ls']) && $_COOKIE['ls']) && !isset($query_parameter["ls"])) {
    $query_string .= ((!empty($query_string)) ? '&' : '') . "ls=" . $_COOKIE["ls"];
  }
  if ((isset($_COOKIE['lsd']) && $_COOKIE['lsd']) && !isset($query_parameter["lsd"])) {
    $query_string .= ((!empty($query_string)) ? '&' : '') . "lsd=" . $_COOKIE["lsd"];
  }
  if (!empty($query_string)) {
    $query_string = "?" . $query_string;
  }
  return $query_string;
}

/**
 * @param $variables
 */
function marketo_form_template_variables(&$variables) {
  $node = $variables['node'];
  $lang = $_COOKIE['language'];
  $regLang = $_COOKIE['regLang'];
  $myIFrameUrlField = "field_iframe_url_" . $node->field_mkt_frm_default_lang[LANGUAGE_NONE][0]['value'];
  $myIFrameUrl = $node->$myIFrameUrlField;
  $iFrameUrl = "";
  $bottomContent = "";
  $iFrameHeight = trim($node->field_iframe_height[LANGUAGE_NONE][0]['value']);
  if (isset($myIFrameUrl[LANGUAGE_NONE][0]['value'])) {
    $iFrameUrl = $myIFrameUrl[LANGUAGE_NONE][0]['value'];
    $myContentField = "field_bottom_content_" . $node->field_mkt_frm_default_lang[LANGUAGE_NONE][0]['value'];
    $myContent = $node->$myContentField;
    $bottomContent = isset($myContent[LANGUAGE_NONE][0]['value']) ? $myContent[LANGUAGE_NONE][0]['value'] : '';

    $iFrameLangType = $lang;
    if ($lang == "en") {
      if ($_COOKIE["regLang"] == "EN-EU" || $_COOKIE["regLang"] == "EN-IN") {
        $iFrameLangType = str_replace("-", "_", strtolower($_COOKIE["regLang"]));
      }
    }
    if ($iFrameLangType != $node->field_mkt_frm_default_lang[LANGUAGE_NONE][0]['value']) {
      $newUrlField = "field_iframe_url_" . $iFrameLangType;
      $newUrl = $node->$newUrlField;
      if (isset($newUrl[LANGUAGE_NONE][0]['value'])) {
        $iFrameUrl = $newUrl[LANGUAGE_NONE][0]['value'];
        $newContentField = "field_bottom_content_" . $iFrameLangType;
        $newContent = $node->$newContentField;
        $bottomContent = $newContent[LANGUAGE_NONE][0]['value'];
      }
    }
  }
  if (strtolower($node->field_display_footer[LANGUAGE_NONE][0]['value']) == '1') {
    $marketo_form_footer = variable_get('marketo_form_footer_' . strtolower($regLang), '');
    $format = db_query("SELECT format FROM filter_format WHERE name = :name", array(':name' => 'Full HTML'))->fetchField();
    $marketo_form_footer = check_markup($marketo_form_footer, $format, $langcode = '' /* TODO Set this variable. */, FALSE);
  }
  else {
    $marketo_form_footer = '';
  }
  $marketo_form = marketo_form_get_form_html($iFrameUrl, $iFrameHeight);
  $ip_embargoed = false;
  $iFrameHeight = '100%';
  if (isset($node->field_iframe_height[LANGUAGE_NONE][0]['value'])) {
    $iFrameHeight = trim($node->field_iframe_height[LANGUAGE_NONE][0]['value']);
  }
  if ($node->field_export_control[LANGUAGE_NONE][0]['value'] == "1") {
    if (function_exists('findit_get_client_ip')) {
      $ip_address = findit_get_client_ip();
      $ip_embargoed = findit_embargoed_ip_address($ip_address);
    }
    else {
      $ip_embargoed = FALSE;
    }
    if (strpos($marketo_form, "jQuery.noConflict")) {
      $export_control_url = 'http://' . $_SERVER['HTTP_HOST'] . '/' . path_to_theme() . '/expctrl/?';
      drupal_add_js('var export_control_url = "' . $export_control_url . '";', array('type' => 'inline'));
      drupal_add_js(drupal_get_path('module', 'marketo_form') . '/marketo_form.js', array('scope' => 'footer'));
    }
  }

  $do_not_translate = isset($node->do_not_translate) ? 'class="OneLinkNoTx"' : '';
  $variables['do_not_translate'] = $do_not_translate;
  $variables['marketo_form'] = $marketo_form;
  $variables['iFrameHeight'] = $iFrameHeight;
  $variables['ip_embargoed'] = $ip_embargoed;
  $variables['bottomContent'] = $bottomContent;
  $variables['marketo_form_footer'] = $marketo_form_footer;
}
