<?php
/**
 * @file custom_blocks.module
 */
// TODO: The first three are view blocks that appear only on the Products page. Move these to the Product module, along with the view definitions.
// TODO: The Blog subscription form is, as far as I can tell, never used. I'm deprecating it. - rositis 10/10/2017


/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function custom_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'subscribe_blog':
      $block['subject'] = 'Blog Subscription';
      $block['content'] = drupal_get_form('blog_subscription_form');
      break;
    default:
  }
  return $block;
}


function blog_subscription_form($form, &$form_state){
  $form = array();
	$form['#attached']['js'] = array(
		drupal_get_path('module', 'custom_blocks') . '/js/custom_blocks.js',
	);
	//$form['#action'] = url('http://localhost/my_assignments/blog-subscribe.php');
  $form['blog_email'] = array(
    '#type' => 'textfield',
    '#size' => 20,
    '#attributes' => array('placeholder'=>t('Email address')),
  );
	$form['lpId'] = array(
		'#type' => 'hidden',
		'#value'=> 15781
	);
	$form['subId'] = array(
		'#type' => 'hidden',
		'#value'=> 217
	);
	$form['munchkinId'] = array(
		'#type' => 'hidden',
		'#value'=> '709-HGB-925'
	);
	$form['kw'] = array(
		'#type' => 'hidden',
		'#value'=> ''
	);
	$form['cr'] = array(
		'#type' => 'hidden',
		'#value'=> ''
	);
	$form['searchstr'] = array(
		'#type' => 'hidden',
		'#value'=> ''
	);
	$form['lpurl'] = array(
		'#type' => 'hidden',
		'#value'=> 'http://info.flukenetworks.com/CIONewsletterSubscription.html?cr={creative}&kw={keyword}'
	);
	$form['formid'] = array(
		'#type' => 'hidden',
		'#value'=> 3574
	);
	$form['returnURL'] = array(
		'#type' => 'hidden',
		'#value'=> 'http://www.flukenetworks.com/content/cio-newsletter-subscribed'
	);
	$form['retURL'] = array(
		'#type' => 'hidden',
		'#value'=> 'http://www.flukenetworks.com/content/cio-newsletter-subscribed'
	);
	$form['returnLPId'] = array(
		'#type' => 'hidden',
		'#value'=> -1
	);
	$form['_mkt_disp'] = array(
		'#type' => 'hidden',
		'#value'=> 'return'
	);
	$form['_mkt_trk'] = array(
		'#type' => 'hidden',
		'#value'=> 'id:709-HGB-925&token:_mch-flukenetworks.com-1360694405383-21882'
	);
	$form['blog_signup_link'] = array(
		'#prefix' => '<div class="btn_143w blog-signup-link">',
		'#type' => 'link',
		'#title' => t('Sign Up'),
		'#href' => '',
		'#suffix'=> '</div>',
		'#attributes' => array('id'=>'blog-signup')
	);
  return $form;
}
