<?php
// $Id$

/**
 * @file
 * Module file for the Application Visibility app
 *
 */

/**
 * Implements hook_menu().
 */
function app_visibility_menu() {
  $items = array();
  $items['app_visibility'] = array(
    'title' => 'Application Visibility',
    'description' => 'TruView Live Application Visibility Worksheet',
    'page callback' => 'app_visibility_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function app_visibility_theme($existing, $type, $theme, $path) {
  $hooks = array();
  $hooks['app_visibility'] = array(
    'template' => 'theme/app_visibility',
    'variables' => array(),
  );
  return $hooks;
}

function app_visibility_page() {
  drupal_add_css(drupal_get_path('module', 'app_visibility') . '/css/app_visibility.css');
  drupal_add_css(drupal_get_path('module', 'app_visibility') . '/css/jquery.steps.css');
  drupal_add_css(drupal_get_path('module', 'app_visibility') . '/css/main.css');
  drupal_add_css(drupal_get_path('module', 'app_visibility') . '/css/normalize.css');
  drupal_add_js(drupal_get_path('module', 'app_visibility') . '/javascript/jquery.steps.min.js');
  drupal_add_js(drupal_get_path('module', 'app_visibility') . '/javascript/app_visibility.js', array('scope' => 'footer'));
  return theme('app_visibility');
}

