<?php

/**
 * @file
 * Hook implementations for the Alternative Language (Pathauto) module.
 */

/**
 * Implements hook_pathauto_alias_alter().
 *
 * It's possible that a language neutral page can be added below a page with
 * a specific language or vice versa. This will break any pathauto tokens
 * that act upon the parent.
 */
function alternative_language_pathauto_pathauto_alias_alter(&$alias, &$context) {

  // Load active trail so we can determine what the language is of the parent.
  $trail = menu_get_active_trail();
  array_pop($trail);

  // Only load a new alias if there is a parent menu item.
  if (count($trail)) {
    $parent = array_pop($trail);

    // Only load a new alias if the language of the parent menu item is
    // different from the node that is being added.
    if ($parent['language'] != $context['language']) {
      $new_alias = token_replace(
        $context['pattern'],
        $context['data'],
        array(
          'sanitize' => FALSE,
          'clear'    => TRUE,
          'callback' => 'pathauto_clean_token_values',
          'language' => (object) array('language' => $parent['language']),
          'pathauto' => TRUE,
        )
      );

      // Check if the token replacement has not actually replaced any values. If
      // that is the case, then stop because we should not generate an alias.
      // @see token_scan()
      $pattern_tokens_removed = preg_replace('/\[[^\s\]:]*:[^\s\]]*\]/', '', $context['pattern']);
      if ($new_alias === $pattern_tokens_removed) {
        return '';
      }

      $alias = pathauto_clean_alias($new_alias);
    }
  }
}
