<?php
/**
 * @file
 * Code for the Blog Fnet feature.
 */

/**
 * Implements hook_preprocess_page().
 */
function blog_fnet_preprocess_page(&$variables) {
  // Hide default page title for the Blog pages.
  if (isset($variables['node']) && $variables['node']->type == 'blog_article') {

    // Hide title for this content type.
    $variables['title'] = '';

  }
}

/**
 * Implements hook_views_api()
 */
function blog_fnet_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'blog_fnet') . '/views',
  );
}