<?php
/*
 * The Page Story and Page Article content types should be here. They really should be
 * structured differently, so if you are reading this, please understand
 * that it wasn't my mess...well, not as much, really, and that I tried to clean
 * it up in the time allotted.
 *
 * At the time of this writitng, I'm trying to get the site to be hosted on Pantheon.
 * I've also had a hell of a month, being sick almost every day. I hope I can
 * hang on.
 *
 * Let's add a menu for Linkware Live and hook_block for some various other stuff.
 * Maybe we'll add a short template for giggles.
 *
 * Thanks for understanding.
 *
 * Ryan Ositis
 */


/**
 * Implements hook_block_info().
 *
 * @return mixed
 */
function microsites_block_info() {
  $block['linkwarelive_footer'] = [
    'info' => t('Linkware Live Footer'),
    'region' => 'footer',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'linkwarelive\nlinkwarelive/*',
  ];
  return $block;
}

/**
 * Implements hook_block_view().
 *
 * @param $delta
 * @return array
 */
function microsites_block_view($delta) {
  $block = [];
  switch ($delta) {
    case 'linkwarelive_footer':
      $block['subject'] = NULL;
      try{
        $block['content'] = theme('linkwarelive_footer');
      }
      catch (Exception $e) {
        watchdog('microsites', $e->getMessage());
      }
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 *
 * @return array
 */
function microsites_theme() {
  $base = [
    'path' => drupal_get_path('module', 'microsites') . '/theme',
  ];
  return [
    'linkwarelive_footer' => $base + [
        'template' => 'linkwarelive_footer',
        'variables' => [],
      ],
  ];
}

/**
 * Implements hook_views_api().
 *
 * @return array
 */
function microsites_views_api() {
  return [
    'api' => 3.0,
    'path' => drupal_get_path('module', 'microsites') . '/views',
  ];
}