<?php

/*
 * The Page Story and Page Article content types should be here. They really should be
 * structured differently, so if you are reading this, please understand
 * that it wasn't my mess...well, not as much, really, and that I tried to clean
 * it up in the time allotted.
 *
 * At the time of this writitng, I'm trying to get the site to be hosted on Pantheon.
 * I've also had a hell of a month, being sick almost every day. I hope I can
 * hang on.
 *
 * Let's add a menu for Linkware Live and hook_blocx for some various other stuff.
 * Maybe we'll add a short template for giggles.
 *
 */


/**
 * Implements hook_block_info().
 *
 * @return mixed
 */
function microsites_block_info() {
  $block['linkwarelive_footer'] = array(
    'info' => t('Linkware Live Footer'),
    'region' => 'footer',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => 'linkwarelive\nmlinkwarelive/*',
  );
  return $block;
}

/**
 * Implements hook_block_view().
 *
 * @param $delta
 * @return array
 */
function microsites_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'linkwarelive_footer':
      $block['subject'] = t('LinkwareLive Footer');
      try{
        $block['content'] = theme('linkwarelive_footer');
      }
      catch (Exception $e) {
        watchdog('microsites', $e->getMessage());
      }
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 *
 * @return array
 */
function microsites_theme() {
  $base = array(
    'path' => drupal_get_path('module', 'microsites') . '/theme',
  );
  return array(
    'linkwarelive_footer' => $base + array(
        'template' => 'linkwarelive_footer',
        'variables' => array(),
      ),
  );
}

/**
 * Implements hook_views_api().
 *
 * @return array
 */
function microsites_views_api() {
  return [
    'api' => 3.0,
    'path' => drupal_get_path('module', 'microsites') . '/views',
  ];
}