<?php
/**
 * @file
 * Code for the Solutions feature.
 */

include_once 'solutions.features.inc';

function solutions_preprocess_page(&$variables) {
  // Add Tabs UI library for the Expertise Role, Topic and Industry page layouts.
  if (isset($variables['node']) && ($variables['node']->type == 'exp_tpc' || $variables['node']->type == 'exp_rle' || $variables['node']->type == 'exp_ind')) {
    // Adds the library making it available for use.
    drupal_add_library('system', 'ui.tabs');
    // Hide title for these page types.
    $variables['title'] = '';
  }
}

/**
 * Implements hook_node_view().
 */
function solutions_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full') {
    $temp = $node->title;
  }
}