<?php

/**
 * @file
 * knowledgebase.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function knowledgebase_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-knowledge_base_article-body'.
  $field_instances['node-knowledge_base_article-body'] = array(
    'bundle' => 'knowledge_base_article',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'field_formatter_filter' => NULL,
        ),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'field_formatter_filter' => NULL,
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'entity_translation_sync' => FALSE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'node-knowledge_base_article-field_article_author'.
  $field_instances['node-knowledge_base_article-field_article_author'] = array(
    'bundle' => 'knowledge_base_article',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Fill out this field to override the author name that is displayed automatically. If left empty the author name will be taken automatically from the user account that originally created this article.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(
          'field_formatter_filter' => NULL,
        ),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_article_author',
    'label' => 'Article Author',
    'required' => 0,
    'settings' => array(
      'entity_translation_sync' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'node-knowledge_base_article-field_knowledge_base'.
  $field_instances['node-knowledge_base_article-field_knowledge_base'] = array(
    'bundle' => 'knowledge_base_article',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Associate the Knowledge Base article with a product name by selecting from the 3rd level of the categorized list.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'entityreference',
        'settings' => array(
          'bypass_access' => FALSE,
          'link' => FALSE,
        ),
        'type' => 'entityreference_label',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_knowledge_base',
    'label' => 'Knowledge Base',
    'required' => 1,
    'settings' => array(
      'behaviors' => array(
        'taxonomy-index' => array(
          'status' => TRUE,
        ),
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Article Author');
  t('Associate the Knowledge Base article with a product name by selecting from the 3rd level of the categorized list.');
  t('Body');
  t('Fill out this field to override the author name that is displayed automatically. If left empty the author name will be taken automatically from the user account that originally created this article.');
  t('Knowledge Base');

  return $field_instances;
}
