<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Implements hook_menu().
 */
function globallink_beans_menu() {
  $items = array();

  $items ['admin/globallink-translations/dashboard/beans'] = array(
    'title' => ' Beans ',
    'page callback' => 'globallink_beans_dashboard',
    'access callback' => 'globallink_access_callback_any',
    'type' => MENU_LOCAL_TASK,
    'file' => 'globallink_beans_send.inc',
    'weight' => 10,
    'page arguments' => array('beans'),
  );

  $items ['admin/globallink-translations/activeSubmissions/beans'] = array(
    'title' => ' Beans ',
    'page callback' => 'globallink_beans_active_submissions',
    'access callback' => 'globallink_access_callback_any',
    'file' => 'globallink_beans_active_submissions.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'page arguments' => array('beans'),
  );

  $items ['admin/globallink-translations/receiveTranslation/beans'] = array(
    'title' => ' Beans ',
    'page callback' => 'globallink_beans_receive_submissions',
    'access callback' => 'globallink_access_callback_any',
    'file' => 'globallink_beans_receive.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'page arguments' => array('beans'),
  );

  $items['admin/globallink-translations/receiveTranslation/beans/preview'] = array(
    'title' => 'Preview Translation',
    'page callback' => 'globallink_beans_preview_translated_content',
    'file' => 'globallink_beans_receive.inc',
    'access arguments' => array(TPT_ROLE_MANAGE_TRANSLATIONS),
    'type' => MENU_CALLBACK,
  );

  return $items;
}