<?php
// $Id: asset_gateway.module 5832 2015-04-07 17:51:42Z sogden1 $

/**
 * @file Custom functionality for the 'asset gateway' node type
 *
 */

/**
 * Implements hook_preprocess_page().
 *
 * @param $variables
 */
function asset_gateway_preprocess_node(&$variables) {
  if ($variables['type'] != 'asset_gateway') {
    return;
  }
  $node = $variables['node'];
  // do not use 'url' value as it strips args, use 'display_url'
  $redirect_url = fnet_common_get_field_value('node', $node, 'field_ag_redirect', 'display_url');
  if (function_exists('findit_local_auth_cookie')) {
    if (preg_match('%findit/(\d{1,8})%im', $redirect_url, $matches)) {
      $document_id = $matches[1];
      findit_local_auth_cookie($document_id);
    }
  }

  $redirect_wait = fnet_common_get_field_value('node', $node, 'field_ag_redirect_wait');

  if (isset($node->page_title)) {
    $page_title = trim($node->page_title);
    drupal_set_title($page_title);
  }

  // editors have the option to NOT set a redirect, in which case they stay on the page.
  if (!empty($redirect_url) && $redirect_wait > 0) {
    $javascript = "setTimeout(\"location.href = \'$redirect_url\';\", $redirect_wait * 1000);";
    drupal_add_js($javascript, array('type' => 'inline', 'scope' => 'footer', 'cache' => FALSE, 'preprocess' => FALSE));
  }

  if (!empty($variables['#node']->field_ag_tracking_code)) {
    $variables['title_suffix'] = array('#markup' => $variables['#node']->field_ag_tracking_code[LANGUAGE_NONE][0]['value']);
  }
}

/**
 * Implements hook_node_view().
 *
 * @param $node
 * @param $view_mode
 * @param $langcode
 */
function asset_gateway_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'asset_gateway') {
    if ($view_mode == 'full') {
      $redirect_url = fnet_common_get_field_value('node', $node, 'field_ag_redirect', 'display_url');
      $redirect_wait = fnet_common_get_field_value('node', $node, 'field_ag_redirect_wait');
      $download_button = fnet_common_get_field_value('node', $node, 'field_add_download_button');
      if (!empty($redirect_url) && empty($redirect_wait) && $download_button) {
        $download_button_text = fnet_common_get_field_value('node', $node, 'field_download_button_text');
        $button = array(
          'class' => 'btn_fat',
          'link' => l($download_button_text, $redirect_url, array('attributes' => array('target' => '_blank')))
        );
        $button = theme('fnet_button', $button);
        if (preg_match('/<%button%>/im', $node->content['body'][0]['#markup'])) {
          $markup = strtr($node->content['body'][0]['#markup'], array('<%button%>' => $button));
          $node->content['body'][0]['#markup'] = $markup;
        }
        else {
          $node->content['button']['#markup'] = '<div style="text-align: center;">' . $button . '</div>';
        }
      }
    }
  }
}

