<?php
/**
 * @file
 * Primary hook implementations.
 */

/**
 * Implements hook_menu().
 */
function metatag_page_title_importer_menu() {
  $items['admin/config/search/metatags/pt_importer'] = array(
    'title' => 'Page Title Importer',
    'description' => 'Migrate data from the Drupal 6 Page Title module to the Drupal 7 Metatag module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_page_title_importer_form'),
    'access arguments' => array('administer meta tags'),
    'file' => 'metatag_page_title_importer.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
