<?php

/**
 * @file
 * Code for the Media Gallery
 */


/*
*   hook_node_view($node, $view_mode, $langcode)
*/
/*
function media_gallery_node_view($node, $view_mode='full') {

	if ($node->type == 'media_gallery') {

	}


}
*/

/*
*   hook_theme()
*/
function media_gallery_theme() {
    $themes = array (

    	'gallery_video_embed' => array(
    		'template' => 'gallery_video_embed',
    		'variables' => array('element' => NULL),
    		),
    );
    return $themes;
}






/*
*   hook_field_formatter_info()
*/
function media_gallery_field_formatter_info() {

	return array(
	    'link_video_embed' => array(
	      'label' => t('URL, Embedded (YouTube)'),
	      'field types' => array('link_field', ),
	      'multiple values' => 2,
	      'settings' => array(),
	      'module' => 'media_gallery',
	    ),

    );

}

/*
*   hook_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display)
*/
function media_gallery_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

	if ( ($entity_type == 'node') && ($field['field_name'] == 'field_gallery_video_url') ) {

		$elements = array();
		$path = drupal_get_path('module', 'media_gallery');

		foreach ($items as $item) {
			$element = array(
				'title'	=> $item['title'],
				'display_url' => $item['display_url'],
				);
			// Get the youtube ID from the query string, if it exists
			if ( isset($item['query']) && isset($item['query']['v']) ) {
				$element['video_id'] = $item['query']['v'];
			}

			$elements[] = $element;

		}

		$return = array(
			'#theme' => 'gallery_video_embed',
			'#element' => array('videos' => $elements),
			);

		return $return;

	}

}



/*
*   hook_entity_view($entity, $type, $view_mode, $langcode)
*/
/*
function media_gallery_entity_view($entity, $type, $view_mode, $langcode) {

	if ( ($type == 'node') && ($entity->type == 'media_gallery') ) {

	}

}

*/

// views-exposed-form-media-default-media-browser-1
//
/*
*   hook_form_alter(&$form, &$form_state, $form_id)
*/

function media_gallery_form_alter(&$form, &$form_state, $form_id) {

	$media_form_ids = array('media_gallery_node_form', 'file_entity_add_upload');

	if ( $form_id  == 'views_exposed_form' ) {

	}


	if (! in_array($form_id, $media_form_ids) ) return;

	if ( $form_id  == 'media_gallery_node_form' ) {

		$info = field_info_field('field_box_gallery_id');

		$path = drupal_get_path('module', 'media_gallery');
		$form['#attached']['css'][] =  $path . '/media_gallery.css';
		$form['group_settings']['#weight']=50;

		$node = $form['#node'];

		// open field groups with content
		if ( fnet_common_get_field_values('node', $node, 'field_gallery_file')  ) {
			$form['#groups']['group_other']->format_settings['formatter'] = 'open';
		}

		if ( fnet_common_get_field_values('node', $node, 'field_media_images') ) {
			$form['#groups']['group_media_images']->format_settings['formatter'] = 'open';
		}

		if ( fnet_common_get_field_values('node', $node, 'field_box_gallery_id')  ) {
			$form['#groups']['group_media_box']->format_settings['formatter'] = 'open';
		}

		if ( fnet_common_get_field_values('node', $node, 'field_gallery_video_url')  ) {
			$form['#groups']['group_videos']->format_settings['formatter'] = 'open';
		}


		$form['locations']['#group']='group_unused';
		$form['menu']['#group']='group_unused';
		$form['print']['#group']='group_unused';
		$form['path']['#group']='group_unused';
		$form['metatags']['#group']='group_unused';
		$form['redirect']['#group']='group_unused';
		$form['xmlsitemap']['#group']='group_unused';
		$form['author']['#group']='group_unused';
		$form['menu']['#group']='group_unused';

		$form['#group_children']['author']='group_unused';
		$form['#group_children']['print']='group_unused';
		$form['#group_children']['menu']='group_unused';

	}

	if ($form_id == 'file_entity_add_upload') {
	
	}

}

/*
function _media_gallery_media_browser_plugin_info_alter(&$info) {


	unset( $info['media_default--media_browser_1'] );
	unset( $info['media_default--media_browser_my_files'] );
	
}
*/

/*
function media_gallery_image_render_modes() {

	$modes= array(
		'full'	=>	'Full Size',
		'product_carousel'	=>	'Carousel',
		'filename'	=>	'File Name',
	);

	 $image_styles = image_styles();
	 foreach ($image_styles as $id => $is) {
	 	$modes['thumb.' . $id] = 'Thumbnail: ' . $is['label'];
	 }

	return $modes;

}

*/