<?php
// $Id:  $

/**
 * @file
 * Code related to the FNET/NS site split.
 *
 */

function site_split_menu() {
  $items = array();
  $items['admin/fnet/site_split/settings'] = array(
    'title' => 'Site Split Settings',
    'description' => 'Settings for site_split module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('site_split_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'site_split.admin.inc',
  );
  return $items;
}

function site_split_personality_tids() {
  $business_entity_tids = array(
    'netscout' => array(533, 537), //netscout, both
    'fnet' => array(534, 537), //dci, both
    'pre-split' => array(533, 534, 537), //netscout, dci, both
  );
  $personality = strtolower(variable_get('site_split_personality', 'Pre-split'));
  return $business_entity_tids[$personality];
}

/**
 * Implements hook_views_api()
 */
function site_split_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'site_split') . '/views',
  );
}
